### ISSUE TITLE
Compatibility crash with modularrouters

### ISSUE THREAD

**Issue by sciguyryan** [Tslat/SmartBrainLib#23]
Hi.

I noticed the following crash while upgrading Occultism (which now depends on SmartBrainLib).

`Exception caught from launcher java.lang.reflect.InvocationTargetException 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) Caused by: java.lang.module.ResolutionException: Modules forgebrainlib and smartbrainlib export package net.tslat.smartbrainlib to module modularrouters 	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901) 	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815) 	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736) 	at java.base/java.lang.module.Resolver.finish(Resolver.java:380) 	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140) 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) 	... 8 more Exiting with ERROR Process exited with code 2.`

I currently don't have any further information on this and have reverted back to an older version of Occultism until I have an idea of what is causing this problem.

**Comment by Tslat** [comment]
Provide the crash report file

**Comment by klikli-dev** [comment]
That is on me the way it looks - @sciguyryan please delete ForgeBrainLib from your mods folder after updating occultism, that should fix it

**Comment by sciguyryan** [comment]
> That is on me the way it looks - @sciguyryan please delete ForgeBrainLib from your mods folder after updating occultism, that should fix it

Thanks, that does appear to have fixed it. I'd not have added it save for the fact it wouldn't let me boot without it.

Thanks for your prompt response here!
