### ISSUE TITLE
SmartBrainLib 1.12 on Minecraft 1.20.4 with Fabric 0.91.1 error: Namespace (named) does not match current runtime namespace (intermediary)

### ISSUE THREAD

**Issue by lospejos** [Tslat/SmartBrainLib#51]
Error using `SmartBrainLib 1.12` on `Minecraft 1.20.4` with `Fabric 0.91.1`: Namespace (named) does not match current runtime namespace (intermediary). Details:

```
java.lang.RuntimeException: Failed to read accessWidener file from mod smartbrainlib
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:512)
	... 6 more
```

Mods installed:

```
[17:00:02] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.1
[17:00:02] [main/INFO]: Loading 128 mods:
	- areas 5.2
	- badpackets 0.5.4
	- better_end_sky 0.2.1+1.20
	- collective 7.13
	- detailab 2.6.3+1.20.4-fabric
	- durabilitytooltip 1.1.5
	- dynamic_fps 3.2.1
	- dynamiccrosshair 7.6+1.20.3
	   \-- yaclx 1.10+1.20
	- entity_model_features 1.2
	- entity_texture_features 5.0
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- fabric-api 0.91.1+1.20.4
	   |-- fabric-api-base 0.4.34+f31bf88132
	   |-- fabric-api-lookup-api-v1 1.6.44+9468a19d32
	   |-- fabric-biome-api-v1 13.0.14+9468a19d32
	   |-- fabric-block-api-v1 1.0.13+73761d2e32
	   |-- fabric-block-view-api-v2 1.0.2+73761d2e32
	   |-- fabric-blockrenderlayer-v1 1.1.44+f4b7e42432
	   |-- fabric-client-tags-api-v1 1.1.5+86b1264532
	   |-- fabric-command-api-v1 1.2.39+f71b366f32
	   |-- fabric-command-api-v2 2.2.18+23e8616e32
	   |-- fabric-commands-v0 0.2.56+df3654b332
	   |-- fabric-containers-v0 0.1.80+df3654b332
	   |-- fabric-content-registries-v0 5.0.8+9468a19d32
	   |-- fabric-convention-tags-v1 1.5.8+9468a19d32
	   |-- fabric-crash-report-info-v1 0.2.21+f4b7e42432
	   |-- fabric-data-generation-api-v1 13.1.16+1b2a41bc32
	   |-- fabric-dimensions-v1 2.1.59+a2e8758a32
	   |-- fabric-entity-events-v1 1.5.26+9468a19d32
	   |-- fabric-events-interaction-v0 0.6.13+9468a19d32
	   |-- fabric-events-lifecycle-v0 0.2.70+df3654b332
	   |-- fabric-game-rule-api-v1 1.0.44+6f7ba8f232
	   |-- fabric-item-api-v1 2.1.33+9468a19d32
	   |-- fabric-item-group-api-v1 4.0.19+f6e85ac232
	   |-- fabric-key-binding-api-v1 1.0.39+f4b7e42432
	   |-- fabric-keybindings-v0 0.2.37+df3654b332
	   |-- fabric-lifecycle-events-v1 2.2.28+9468a19d32
	   |-- fabric-loot-api-v2 2.1.3+6f9f09e032
	   |-- fabric-message-api-v1 6.0.3+ebb1549632
	   |-- fabric-mining-level-api-v1 2.1.58+f4b7e42432
	   |-- fabric-model-loading-api-v1 1.0.6+9468a19d32
	   |-- fabric-models-v0 0.4.5+9386d8a732
	   |-- fabric-networking-api-v1 3.1.1+901470e432
	   |-- fabric-object-builder-api-v1 13.0.6+a2e8758a32
	   |-- fabric-particles-v1 1.1.5+f4b7e42432
	   |-- fabric-recipe-api-v1 2.0.14+23e8616e32
	   |-- fabric-registry-sync-v0 4.0.12+9468a19d32
	   |-- fabric-renderer-api-v1 3.2.2+2034447c32
	   |-- fabric-renderer-indigo 1.5.2+2034447c32
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b332
	   |-- fabric-rendering-data-attachment-v1 0.3.40+73761d2e32
	   |-- fabric-rendering-fluids-v1 3.0.31+f4b7e42432
	   |-- fabric-rendering-v0 1.1.52+df3654b332
	   |-- fabric-rendering-v1 3.0.11+9468a19d32
	   |-- fabric-resource-conditions-api-v1 2.3.12+de5c6cca32
	   |-- fabric-resource-loader-v0 0.11.14+f31bf88132
	   |-- fabric-screen-api-v1 2.0.15+f6e85ac232
	   |-- fabric-screen-handler-api-v1 1.3.49+9468a19d32
	   |-- fabric-sound-api-v1 1.0.15+f4b7e42432
	   |-- fabric-transfer-api-v1 4.0.5+aaf9c96932
	   \-- fabric-transitive-access-wideners-v1 5.0.12+1b2a41bc32
	- fabric-language-kotlin 1.10.16+kotlin.1.9.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- fusion 1.1.0+c
	- geckolib 4.3.1
	   \-- com_eliotlash_mclib_mclib 20
	- immediatelyfast 1.2.8+1.20.4
	   \-- net_lenni0451_reflect 1.3.1
	- iris 1.6.13
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 13.1.0
	- java 21
	- languagereload 1.5.10+1.20.3
	- midnightlib 1.5.1
	- minecraft 1.20.4
	- modernfix 5.10.0+mc1.20.3
	   \-- mixinextras 0.3.1
	- modmenu 9.0.0-pre.1
	- nochatreports 1.20.4-v2.5.0
	   |-- fabric-api-base 0.4.34+f31bf88132
	   |-- fabric-networking-api-v1 3.1.1+901470e432
	   |-- fabric-rendering-v1 3.0.11+9468a19d32
	   |-- fabric-resource-loader-v0 0.11.14+f31bf88132
	   \-- fabric-screen-api-v1 2.0.15+f6e85ac232
	- polymer-bundled 0.7.1+1.20.4
	   |-- polymer-autohost 0.7.1+1.20.4
	   |-- polymer-blocks 0.7.1+1.20.4
	   |-- polymer-common 0.7.1+1.20.4
	   |    \-- packet_tweaker 0.5.0+1.20.2-rc1
	   |-- polymer-core 0.7.1+1.20.4
	   |    |-- polymer-networking 0.7.1+1.20.4
	   |    |    \-- polymer-common 0.7.1+1.20.4
	   |    |         \-- packet_tweaker 0.5.0+1.20.2-rc1
	   |    \-- polymer-registry-sync-manipulator 0.7.1+1.20.4
	   |-- polymer-resource-pack 0.7.1+1.20.4
	   |    \-- polymer-common 0.7.1+1.20.4
	   |         \-- packet_tweaker 0.5.0+1.20.2-rc1
	   \-- polymer-virtual-entity 0.7.1+1.20.4
	        \-- polymer-common 0.7.1+1.20.4
	             \-- packet_tweaker 0.5.0+1.20.2-rc1
	- randomvillagenames 3.4
	- reeses-sodium-options 1.7.0+mc1.20.2-build.97
	- repurposed_structures 7.2.2+1.20.3-fabric
	- smartbrainlib 1.12
	- sodium 0.5.4
	- sodium-extra 0.5.3+mc1.20.2-build.114
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- supermartijn642configlib 1.1.8+a
	- terrablender 3.3.0.3
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- terralith 2.4.11
	- treeharvester 8.3
	- villagernames 7.1
	- wi_zoom 1.5-MC1.20.4
	- yet_another_config_lib_v3 3.3.1+1.20.4
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zombiehorsespawn 4.7
```

**Comment by Tslat** [comment]
sigh

**Comment by Tslat** [comment]
Found it, it's modrinth being stupid
I'll reupload
